image: ubuntu:bionic

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt -y install wget lsb-release gnupg
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt-get update
          - apt-get -y install
            cmake pkg-config cppcheck libogre-1.9-dev libogre-2.1-dev libglew-dev libfreeimage-dev doxygen ruby-ronn freeglut3-dev libxmu-dev libxi-dev curl git mercurial g++-8 uuid-dev xvfb
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          - gcc -v
          - g++ -v
          - gcov -v
          # Dependency: Ignition packages
          - apt-get -y install
            libignition-cmake2-dev libignition-common3-dev libignition-math6-dev libignition-plugin-dev
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git
          - cd lcov
          - make install
          - cd ..
          # Ignition rendering
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage
          - make -j4
          - make install
          - make codecheck
          # Run tests
          # - Xvfb :1 -screen 0 1280x1024x24 &
          # - DISPLAY=:1.0 make test
          # - DISPLAY=:1.0 RENDER_ENGINE_VALUES=ogre2 MESA_GL_VERSION_OVERRIDE=3.3 make test
          # Build an example
          - cd ../examples/simple_demo
          - mkdir build
          - cd build
          - cmake ..
          - make -j4

