name: DeepX CI

run-name: Build Docker container and perform unit testing

on: [push, workflow_dispatch]

jobs:
  build-library:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: deepx-inc
          password: ${{ github.token }}
      - name: Build the docker container
        run: docker-compose build --build-arg BASE_IMAGE=ghcr.io/deepx-inc/base_images --build-arg TAG=foxy
      - name: Run Docker container and run unit testing inside
        run: |
          docker run --name deepx-gz-rendering-test-container \
          -v $GITHUB_WORKSPACE:/root/gazebo \
          --entrypoint bash \
          --rm \
          -w /root/gazebo \
          deepx-gz-rendering \
          -c 'cd /; pwd; ls; cd /root; pwd; ls; cd /root/gazebo; pwd; ls; cd /root/gazebo/gz-rendering; pwd; ls;'
#          -c 'cd /root/gazebo/gz-rendering/build && ctest'